In [49]:
import numpy as nm  
import matplotlib.pyplot as plt
import pandas as pd 
import sklearn

In [50]:
path = 'dataset\jeeves.csv'

In [51]:
dataset= pd.read_csv(path)

In [52]:
dataset

Day   Outlook  Temp Humidity    Wind Tennis?
0     1     Sunny   Hot     High    Weak      No
1     2     Sunny   Hot     High  Strong      No
2     3  Overcast   Hot     High    Weak     Yes
3     4      Rain  Mild     High    Weak     Yes
4     5      Rain  Cool   Normal    Weak     Yes
5     6      Rain  Cool   Normal  Strong      No
6     7  Overcast  Cool   Normal  Strong     Yes
7     8     Sunny  Mild     High    Weak      No
8     9     Sunny  Cool   Normal    Weak     Yes
9    10      Rain  Mild   Normal    Weak     Yes
10   11     Sunny  Mild   Normal  Strong     Yes
11   12  Overcast  Mild     High  Strong     Yes
12   13  Overcast   Hot   Normal    Weak     Yes
13   14      Rain  Mild     High  Strong      No
14   15     Sunny  Mild     High  Strong      No
15   16      Rain   Hot   Normal  Strong      No
16   17      Rain   Hot     High    Weak     Yes
17   18  Overcast  Mild   Normal    Weak     Yes
18   19  Overcast  Mild     High    Weak     Yes
19   20     Sunny  Mild   Normal    Weak     Yes
20   21     Sunny  Cool     High  Strong      No
21   22     Sunny  Cool     High    Weak      No

In [53]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Day       22 non-null     int64 
 1   Outlook   22 non-null     object
 2   Temp      22 non-null     object
 3   Humidity  22 non-null     object
 4   Wind      22 non-null     object
 5   Tennis?   22 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.2+ KB


In [56]:
outlook = {'Overcast' : 2, 'Sunny': 1, 'Rain': 0}
dataset["Outlook"] = dataset["Outlook"].map(outlook)

temp = {'Cool' : 2, 'Mild': 1, 'Hot': 0}
dataset["Temp"] = dataset["Temp"].map(temp)

humidity = {'High' : 2, 'Mild': 1, 'Normal': 0}
dataset["Humidity"] = dataset["Humidity"].map(humidity)

wind = {'Strong': 1, 'Weak': 0}
dataset["Wind"] = dataset["Wind"].map(wind)

In [60]:
play = {'Yes' : 1, 'No' : 0}
dataset["Tennis?"] = dataset["Tennis?"].map(play)

In [61]:
dataset

Day  Outlook  Temp  Humidity  Wind  Tennis?
0     1        1     0         2     0        0
1     2        1     0         2     1        0
2     3        2     0         2     0        1
3     4        0     1         2     0        1
4     5        0     2         0     0        1
5     6        0     2         0     1        0
6     7        2     2         0     1        1
7     8        1     1         2     0        0
8     9        1     2         0     0        1
9    10        0     1         0     0        1
10   11        1     1         0     1        1
11   12        2     1         2     1        1
12   13        2     0         0     0        1
13   14        0     1         2     1        0
14   15        1     1         2     1        0
15   16        0     0         0     1        0
16   17        0     0         2     0        1
17   18        2     1         0     0        1
18   19        2     1         2     0        1
19   20        1     1         0     0        1
20   21        1     2         2     1        0
21   22        1     2         2     0        0

In [63]:
x= dataset.iloc[:, 1:5].values  
y= dataset.iloc[:, 5].values 

In [64]:
print(x,y)

[[1 0 2 0]
 [1 0 2 1]
 [2 0 2 0]
 [0 1 2 0]
 [0 2 0 0]
 [0 2 0 1]
 [2 2 0 1]
 [1 1 2 0]
 [1 2 0 0]
 [0 1 0 0]
 [1 1 0 1]
 [2 1 2 1]
 [2 0 0 0]
 [0 1 2 1]
 [1 1 2 1]
 [0 0 0 1]
 [0 0 2 0]
 [2 1 0 0]
 [2 1 2 0]
 [1 1 0 0]
 [1 2 2 1]
 [1 2 2 0]] [0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 0 0]


In [67]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [68]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

In [69]:
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [70]:
DecisionTreeClassifier( class_weight=None, 
                        criterion='entropy', 
                        max_depth=None,
                        max_features=None, 
                        max_leaf_nodes=None,
                        min_impurity_decrease=0.0, 
                        # min_impurity_split=None,
                        min_samples_leaf=1, 
                        min_samples_split=2,
                        min_weight_fraction_leaf=0.0, 
                        # presort=False,
                        random_state=0, 
                        splitter='best' )

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [71]:
y_pred= classifier.predict(x_test)

In [72]:
print(y_pred)

[0 0 0 0 0 0]


In [75]:
print(y_test)

[0 1 0 0 0 0]


In [73]:
 
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [74]:
print(cm)

[[5 0]
 [1 0]]
